### PR TITLE
upgrading zookeeper to 3.7.1

### LINKED ISSUE #484: Use zookeeper 3.7.1
### Description

3.7.0 has some security vulnerabilities, some of them has been fixed to 3.7.1

### Importance

must-have

### Suggestions for an improvement

Fix the vulnerabilities

### PR DESCRIPTION
**Pull request by Amit-Singh40**
Signed-off-by: Amit-Singh40 <amit.singh30@dell.com>

### Change log description

Upgraded the zookeeper version to 3.7.1 to fix vulnerabilities in 3.7.0

### Purpose of the change
Fixes #484 

### What the code does

Upgrades the zookeeper to 3.7.1

### How to verify it

Perform jenkins tests: Pravega_ZookeeperOperator, Pravega_Zookeeper_Upgrade and Pravega_ZookeeperOperator_E2E and github build.

### CODE REVIEW

**Review by jkhalack — APPROVED** [review]
LGTM

**Comment by anishakj** [comment]
@Amit-Singh40 Could you please change the version in `docker/zu/build.gradle.kts` as well?

**Review by anishakj — APPROVED** [review]
LGTM

**Comment by AKamyshnikova** [comment]
Any plans publish image with this fix?

**Pull request merged**
