### PR TITLE
Adjust behavior for pod labels

### LINKED ISSUE #511: Pod Labels not applied to StatefulSet
### Description

The `zookeepercluster.spec.pod.labels` are not applied to the final pods or the StatefulSet created by the Zookeeper Operator. 

### Importance

`should-have`: If it's in the spec, it should work as intended or be removed.
`blocker`: Since the Solr Operator uses this Zookeeper Operator, it is currently blocking us from adding custom labels to Zookeeper Clusters created with the Solr Operator. 

### Location

Unsure, would need some help to track it down, but is likely related to https://github.com/pravega/zookeeper-operator/issues/257.

### Suggestions for an improvement

Taking into account the features or https://github.com/pravega/zookeeper-operator/issues/257, this should have a merge between the two maps and apply the final merge to the template spec of the StatefulSet.

### PR DESCRIPTION
**Pull request by endzyme**
### Change log description

Pod labels from the Spec.Pod.Labels were previously not propagated to the StatefulSet.Template.

### Purpose of the change

Resolves #511

### What the code does

- Adds the Spec.Pod.Labels to the creation of the StatefulSet template
- Adds docs to note the differences between the two Label locations in the ZookeeperCluster CRD and denotes priority order

### How to verify it

- Add labels to the Spec.Pod.Labels and expect to have it show up in the pod labels

### CODE REVIEW

**Comment by amuraru** [comment]
looks good to me.

**Review by anishakj — APPROVED** [review]
LGTM

**Comment by endzyme** [comment]
Thanks all!

**Comment by endzyme** [comment]
Any idea when the next release will be?

**Pull request merged**
