### PR TITLE
ISSUE-257 Propagate labels to ZookeeperCluster underlying resources

### PR DESCRIPTION
**Pull request by amuraru**
Fixes: #257

### CODE REVIEW

**Review by spiegela — COMMENTED** [review]
This looks great. I was needing this exact fix myself. Could you also add unit tests for these labels?

**Comment by amuraru** [comment]
added unit tests

**Review by spiegela — APPROVED** [review]
💯 Perfect.  Thanks!

**Review by anishakj — APPROVED** [review]
LGTM

**Comment by endzyme** [comment]
I think this may have broken somewhere along the way. I am unable to propagate labels down to the statefulset nor the pods. I will open an issue for this.

**Comment by endzyme** [comment]
Ah - the problem is that labels from `spec.labels` are propagated to pods, but not `spec.pod.labels`

**Pull request merged**
