### PR TITLE
ISSUE-147 - Upgrade k8s dependencies

### LINKED ISSUE #147: Upgrade controller-runtime library to 0.5
sigs.k8s.io/controller-runtime lib is quite old. 
Updating [to a newer release](https://github.com/kubernetes-sigs/controller-runtime/releases
) is required for new features like https://github.com/pravega/zookeeper-operator/issues/142

@ekarlso had also a lib update script that may be useful to import:
https://github.com/ekarlso/zookeeper-operator/blob/e1201ff33a364c31a2053bbef20a1df4897710d2/scripts/update-kube-version.sh

### PR DESCRIPTION
**Pull request by amuraru**
- upgrade to k8s 1.17.5 deps
- upgrade to operator-sdk 0.17
- upgrade controller-runtime to 0.5.2

Fixes #147

### CODE REVIEW

**Comment by amuraru** [comment]
> whrere is the script update-kube-version.sh called?

good call @anishakj - added it as a Makefile target

**Comment by anishakj** [comment]
Currently, I am doing testing with the changes. Will keep posted.

**Comment by anishakj** [comment]
Could you please resolve the conflicts and re base  to master?

**Comment by amuraru** [comment]
rebased

**Comment by anishakj** [comment]
> Currently, I am doing testing with the changes. Will keep posted.

In my testing I am seeing the below issue.
1. Install zookeeper-operator 0.2.7
2. Create zookeeper cluster
3. upgrade the zookeeper-operator image from 0.2.7 to new image that is built
4. Operator is getting upgraded, but the pods  also getting restarted
```kubectl get po
NAME                                  READY   STATUS        RESTARTS   AGE
zookeeper-0                           1/1     Running       0          15m
zookeeper-1                           1/1     Terminating   0          18m
zookeeper-2                           1/1     Running       0          48s
zookeeper-3                           1/1     Running       0          4m20s
zookeeper-4                           1/1     Running       0          7m44s
zookeeper-operator-6c9f8f5654-sd496   1/1     Running       0          11m
```
Doing further analysis

**Comment by anishakj** [comment]
> > Currently, I am doing testing with the changes. Will keep posted.
> 
> In my testing I am seeing the below issue.
> 
> 1. Install zookeeper-operator 0.2.7
> 2. Create zookeeper cluster
> 3. upgrade the zookeeper-operator image from 0.2.7 to new image that is built
> 4. Operator is getting upgraded, but the pods  also getting restarted
> 
> ```
> NAME                                  READY   STATUS        RESTARTS   AGE
> zookeeper-0                           1/1     Running       0          15m
> zookeeper-1                           1/1     Terminating   0          18m
> zookeeper-2                           1/1     Running       0          48s
> zookeeper-3                           1/1     Running       0          4m20s
> zookeeper-4                           1/1     Running       0          7m44s
> zookeeper-operator-6c9f8f5654-sd496   1/1     Running       0          11m
> ```
> 
> Doing further analysis

Rolling upgrade was happening as termination grace period was changed from 30s to 180s as part of other PR.
I have tested the below scenarios
1. Zookeeper operator upgrade
2. Leader Election by creating operator with 3 replicas
3. Creation and Deletion of zookeeper cluster
4. Scale up/Down of zookeeper cluster
5. Upgrade of zookeeper cluster

**Pull request merged**
