### PR TITLE
Upgrade to golang 1.17 and update dependencies

### PR DESCRIPTION
**Pull request by amuraru**
### Change log description

- Use golang 1.17
- Upgrade k8s deps to 1.20
 

### Purpose of the change

- keep deps up to date

### CODE REVIEW

**Comment by anishakj** [comment]
@amuraru  Can we remove the `v1beta1` version of CRD from charts as well

**Comment by amuraru** [comment]
I'd personally prefer to do that in a separate PR and not here. wdyt?

**Comment by anishakj** [comment]
> I'd personally prefer to do that in a separate PR and not here. wdyt?

sure, that is absolutely fine

**Review by anishakj — APPROVED** [review]
LGTM

**Pull request merged**
