### PR TITLE
Issue 493 Allow operator to recover from FailedUpgrade

### LINKED ISSUE #493: zookeeper stuck in upgrade, cluster seems to be upgraded, alle nodes running the new version, and ready
### Description
cluster is stuck in upgrade, but cluster seems to be ready and upgraded
zookeeper   3          2                3.7.0_0.2.14_2022-08-10   3.7.0_0.2.14_2022-08-29   172.18.81.155:2181   N/A                 91d
so the upgrade was a 0.2.14 running zookeeper 3.7.0, where the baseimage was patched with a few security issues so the same zookeeper and operator, we are doing this regularly, and it usually works, but has also failed a few times. what I have done so-far is to delete the cluster and start over again.. but I really want to mature this (also starting over with a new zk cluster involves some work)

below is the output of 
`kubectl  -n zookeeper get pods -o json | jq -r .items[].status `
`{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:03:38Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:18Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:18Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:03:38Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://c7ae21de50fe3be1964501b78742054c5dba8a63a14c044ffd7b6650c9851f6b",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:10:04Z"
        }
      }
    }
  ],
  "hostIP": "XXX",
  "phase": "Running",
  "podIP": "XX.36",
  "podIPs": [
    {
      "ip": "XX.36"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:03:38Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:16:05Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:24:46Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:24:46Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:16:05Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://f7054bcf807c7e2d6d8c4d4d0b3674e153012f48fa1fc0141aef389ae4268941",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:24:33Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.91",
  "podIPs": [
    {
      "ip": "XX.91"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:16:05Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:52Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:15:32Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:15:32Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:52Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://c4384f795654ccdb1491fb3cce44859297454abe49b79aecc4dac136e969c9dd",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:15:16Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.149",
  "podIPs": [
    {
      "ip": "XX.149"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:10:52Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:56:44Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:57:13Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:57:13Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:56:43Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://33b55840f56795b55594ad5c49bb96a1d917802ad1b598972fda45ec643a767a",
      "image": "ivanhub.azurecr.io/pravega_zookeeper_operator:0.2.14_2022-08-08",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper_operator@sha256:db55ab2ce4784bf78d41e3774ee2e74585c018190f03a8be83cfff5154fa8dd1",
      "lastState": {},
      "name": "zookeeper-operator",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T11:57:13Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.171",
  "podIPs": [
    {
      "ip": "XX.171"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T11:56:44Z"
}
`
### Importance

must-have
### Location
zookeeper-operator
### Suggestions for an improvement
So what I am missing is the option of running commands against the operator to fix issues like this,
I am also not sure where to look for logfiles that would help fixing this isse

### PR DESCRIPTION
**Pull request by lunarfs**
If the upgrade is taking more than the timeout to get back in the cluster) the operator cannot recover even if the cluster is healthy. adding steps to recover once the cluster is completely upgraded (potentially manual work)

### Change log description

Fix operator stuck in FailedUpgrade, even after the cluster is upgraded and healthy.

### Purpose of the change

fixes #493 

### What the code does

Check if the Statefullset is fully upgrade when the operator is in _UpgradeFailed_ mode, if the cluster is fully upgraded and healthy, remove the failed state and complete the upgrade

### How to verify it

make sure that a node will not get online whit-in the 10 min timeout when doing an upgrade
verify that the cluster is stuck in UpgradeFailed and e.g. 2 out of 3 nodes ready
upgrade the operator to a build containing this fix, and verify that the upgrade completes.
obviously if you are already running this version, a failed upgrade vil recover once the cluster is in a good and upgraded state

### CODE REVIEW

**Comment by lunarfs** [comment]
So I applied this to a cluster having the same issue as #493  and the cluster successfully healed

**Comment by anishakj** [comment]
> So I applied this to a cluster having the same issue as #493 and the cluster successfully healed

But there can be issues, when upgrade is failing due to valid reason rt

**Comment by lunarfs** [comment]
> > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> 
> But there can be issues, when upgrade is failing due to valid reason rt

not sure i understand, 

> > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> 
> But there can be issues, when upgrade is failing due to valid reason rt

not sure I understand, so if the statefull set is n/n and the revision is correct what could not be ok?

**Comment by anishakj** [comment]
> > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > 
> > 
> > But there can be issues, when upgrade is failing due to valid reason rt
> 
> not sure i understand,
> 
> > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > 
> > 
> > But there can be issues, when upgrade is failing due to valid reason rt
> 
> not sure I understand, so if the statefull set is n/n and the revision is correct what could not be ok?

Suppose user has given wrong image name or repository during upgrade. In that case upgrade will never succeed and we would like to make upgrade as failed. As the upgrade strategy is `rollingupdate` second pod upgrade wont get started only

**Comment by lunarfs** [comment]
> > > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > > 
> > > 
> > > But there can be issues, when upgrade is failing due to valid reason rt
> > 
> > 
> > not sure i understand,
> > > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > > 
> > > 
> > > But there can be issues, when upgrade is failing due to valid reason rt
> > 
> > 
> > not sure I understand, so if the statefull set is n/n and the revision is correct what could not be ok?
> 
> Suppose user has given wrong image name or repository during upgrade. In that case upgrade will never succeed and we would like to make upgrade as failed. As the upgrade strategy is `rollingupdate` second pod upgrade wont get started only

But i guess in that case the statefulset will not reach n/n but rather (n-1)/n as the pod that have gotten the invalid image applied will never become ready

**Comment by lunarfs** [comment]
> > > > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > > > 
> > > > 
> > > > But there can be issues, when upgrade is failing due to valid reason rt
> > > 
> > > 
> > > not sure i understand,
> > > > > So I applied this to a cluster having the same issue as #493 and the cluster successfully healed
> > > > 
> > > > 
> > > > But there can be issues, when upgrade is failing due to valid reason rt
> > > 
> > > 
> > > not sure I understand, so if the statefull set is n/n and the revision is correct what could not be ok?
> > 
> > 
> > Suppose user has given wrong image name or repository during upgrade. In that case upgrade will never succeed and we would like to make upgrade as failed. As the upgrade strategy is `rollingupdate` second pod upgrade wont get started only
> 
> But i guess in that case the statefulset will not reach n/n but rather (n-1)/n as the pod that have gotten the invalid image applied will never become ready

or is there something i am missing here?

**Review by anishakj — APPROVED** [review]
LGTM

**Pull request merged**
