### PR TITLE
Issue-265-Helm chart version differs from pravega/charts

### LINKED ISSUE #265: Helm chart version differs from pravega/charts
### Description

The ZooKeeper [operator] Helm charts provided in https://github.com/pravega/charts/tree/master/docs have recently been updated to version 0.2.9.
But the version in this repository is still 0.2.8:
- https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/Chart.yaml
- https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/Chart.yaml

### Importance

Not so important in itself, because the charts at version 0.2.9 are available.

### Location

https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/

### Suggestions for an improvement

Could you explain how the charts in https://github.com/pravega/charts/ are produced? I though it was based on the code provided in this repository. But maybe it is actually the case??

### PR DESCRIPTION
**Pull request by Prabhaker24**
Signed-off-by: prabhaker24 <prabhaker.saxena@dell.com>

### Change log description
Helm chart version differs from pravega/charts

### Purpose of the change
Fixes #265 
 
### What the code does
The ZooKeeper [operator] Helm charts provided in https://github.com/pravega/charts/tree/master/docs have recently been updated to version 0.2.9.
But the version in this repository is still 0.2.8:

https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/Chart.yaml
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/Chart.yaml

it fixes the version in both locations to 0.2.9 

### How to verify it
check both locations above in charts.yaml both has version set to 0.2.9.

### CODE REVIEW

**Review by anishakj — APPROVED** [review]
LGTM

**Review by SrishT — CHANGES_REQUESTED** [review]
Could u also change the version inside the values.yaml for the operator and the zookeeper, and also within the deployment manifests?

**Comment by Prabhaker24** [comment]
> Could u also change the version inside the values.yaml for the operator and the zookeeper, and also within the deployment manifests?

Done.

**Review by SrishT — APPROVED** [review]
LGTM

**Comment by dalbani** [comment]
Thank you everyone. 👍

**Pull request merged**
