### PR TITLE
Issue 183: Prefixing service ports with tcp to comply with istio standards

### PR DESCRIPTION
**Pull request by whitleykeith**
Fixes https://github.com/pravega/zookeeper-operator/issues/183 based on this istio issue https://github.com/istio/istio/issues/23991

Also added the client port (2181) to the headless service as many systems that use ZK (Kafka, Solr) will talk to ZKs client port through the headless service.

### CODE REVIEW

**Comment by AceHack** [comment]
Can't wait!! this will really help our istio deployment.

**Comment by Prabhaker24** [comment]
@whitleykeith I am testing these changes we will merge this pr once the testing is completed.

**Comment by Prabhaker24** [comment]
@whitleykeith can you please rebase to master as well

**Comment by whitleykeith** [comment]
rebased

**Comment by anishakj** [comment]
After doing rebase,  changes are  not showing correctly. You may have to just pull from master, rather than doing rebase

**Comment by whitleykeith** [comment]
@anishakj Did you need me to pull from master again? I noticed the email but I don't see the comment you made here

**Comment by anishakj** [comment]
> @anishakj Did you need me to pull from master again? I noticed the email but I don't see the comment you made here

There are 2 issues, there is a conflict in generators.go as well as the change is not rebased on master.
Please follow https://github.com/pravega/zookeeper-operator/wiki/Contributing#issues-and-pull-request and in case of any issues, let us know

**Comment by whitleykeith** [comment]
@anishakj check it now. I ended up messing up some reverts but I think the diff looks good now.

**Pull request merged**
