### PR TITLE
Bump operator-sdk version to v0.18.0

### PR DESCRIPTION
**Pull request by AKamyshnikova**
Updated required modules as well

* k8s.io/api v0.18.2
* k8s.io/apimachinery v0.18.2
* sigs.k8s.io/controller-runtime v0.6.0
* k8s.io/client-go v0.18.2

Fixes: #365

### CODE REVIEW

**Comment by amuraru** [comment]
this is already covered by https://github.com/pravega/zookeeper-operator/pull/367

**Comment by anishakj** [comment]
Closing this PR as it is superseded by  #367

**Comment by AKamyshnikova** [comment]
#367 is fixing log messages, I don't see how it covers operator-sdk update.

**Comment by amuraru** [comment]
I think @anishakj meant #363

**Pull request closed without merging**
